"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
const config_1 = require("prisma/config");
exports.default = (0, config_1.defineConfig)({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        // url: "postgresql://placement_admin:password123@127.0.0.1:5435/placement?sslmode=disable&schema=public",
        url: "postgresql://neondb_owner:npg_V2EXfputakg6@ep-flat-meadow-aocpgazm-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
    },
});
//# sourceMappingURL=prisma.config.js.map