// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // url: "postgresql://placement_admin:password123@127.0.0.1:5435/placement?sslmode=disable&schema=public",
    url: "postgresql://neondb_owner:npg_V2EXfputakg6@ep-flat-meadow-aocpgazm-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
  },
});
